## Word Embedding Techinque using Embedding Layer in Keras

In [4]:
from tensorflow.keras.preprocessing.text import one_hot 

In [14]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good ',]

## Initialize Vocabulary Size

In [15]:
voc_size = 1000

## One Hot Representation

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[433, 930, 290, 523], [433, 930, 290, 457], [433, 913, 290, 602], [136, 532, 78, 615, 529], [136, 532, 78, 615, 29], [534, 433, 870, 290, 394], [173, 425, 419, 615]]


## Word Embedding Representation

In [18]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [19]:
sent_length = 8

In [20]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)

In [21]:
print(embedded_docs)

[[  0   0   0   0 433 930 290 523]
 [  0   0   0   0 433 930 290 457]
 [  0   0   0   0 433 913 290 602]
 [  0   0   0 136 532  78 615 529]
 [  0   0   0 136 532  78 615  29]
 [  0   0   0 534 433 870 290 394]
 [  0   0   0   0 173 425 419 615]]


In [30]:
dim = 15

In [31]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [32]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 15)             15000     
Total params: 15,000
Trainable params: 15,000
Non-trainable params: 0
_________________________________________________________________


In [33]:
print(embedded_docs)

[[  0   0   0   0 433 930 290 523]
 [  0   0   0   0 433 930 290 457]
 [  0   0   0   0 433 913 290 602]
 [  0   0   0 136 532  78 615 529]
 [  0   0   0 136 532  78 615  29]
 [  0   0   0 534 433 870 290 394]
 [  0   0   0   0 173 425 419 615]]


In [34]:
print(model.predict(embedded_docs))

[[[-3.37105878e-02  1.20729320e-02  1.62771977e-02  1.06867924e-02
    1.24062076e-02  3.79203446e-02  1.10804923e-02 -4.42827605e-02
   -3.18481773e-03  4.32939790e-02  1.76514313e-03 -1.14844330e-02
    3.88596766e-02 -3.76546271e-02  1.69719569e-02]
  [-3.37105878e-02  1.20729320e-02  1.62771977e-02  1.06867924e-02
    1.24062076e-02  3.79203446e-02  1.10804923e-02 -4.42827605e-02
   -3.18481773e-03  4.32939790e-02  1.76514313e-03 -1.14844330e-02
    3.88596766e-02 -3.76546271e-02  1.69719569e-02]
  [-3.37105878e-02  1.20729320e-02  1.62771977e-02  1.06867924e-02
    1.24062076e-02  3.79203446e-02  1.10804923e-02 -4.42827605e-02
   -3.18481773e-03  4.32939790e-02  1.76514313e-03 -1.14844330e-02
    3.88596766e-02 -3.76546271e-02  1.69719569e-02]
  [-3.37105878e-02  1.20729320e-02  1.62771977e-02  1.06867924e-02
    1.24062076e-02  3.79203446e-02  1.10804923e-02 -4.42827605e-02
   -3.18481773e-03  4.32939790e-02  1.76514313e-03 -1.14844330e-02
    3.88596766e-02 -3.76546271e-02  1.69

In [35]:
embedded_docs[0]

array([  0,   0,   0,   0, 433, 930, 290, 523])

In [36]:
print(model.predict(embedded_docs)[0])

[[-0.03371059  0.01207293  0.0162772   0.01068679  0.01240621  0.03792034
   0.01108049 -0.04428276 -0.00318482  0.04329398  0.00176514 -0.01148443
   0.03885968 -0.03765463  0.01697196]
 [-0.03371059  0.01207293  0.0162772   0.01068679  0.01240621  0.03792034
   0.01108049 -0.04428276 -0.00318482  0.04329398  0.00176514 -0.01148443
   0.03885968 -0.03765463  0.01697196]
 [-0.03371059  0.01207293  0.0162772   0.01068679  0.01240621  0.03792034
   0.01108049 -0.04428276 -0.00318482  0.04329398  0.00176514 -0.01148443
   0.03885968 -0.03765463  0.01697196]
 [-0.03371059  0.01207293  0.0162772   0.01068679  0.01240621  0.03792034
   0.01108049 -0.04428276 -0.00318482  0.04329398  0.00176514 -0.01148443
   0.03885968 -0.03765463  0.01697196]
 [-0.03741837 -0.03777853  0.03859581  0.02893815 -0.04089592 -0.03926307
  -0.01581348  0.03848307 -0.0400208   0.04329909 -0.00466751 -0.03399372
   0.02523592  0.00054143  0.02067113]
 [-0.0300392   0.01956213 -0.00667138  0.02378703  0.04942289 -0.